In [1]:
import zstandard as zstd 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import chess.pgn
import io

In [4]:
decompressor = zstd.ZstdDecompressor()

In [14]:
with open("lichess_games.zst", "rb") as f:
    reader = decompressor.stream_reader(f)
    text_stream = io.TextIOWrapper(reader, encoding = "utf-8")

    games = []
    while True:
        game = chess.pgn.read_game(text_stream)
        if game is None: 
            break

        headers = game.headers
        if (headers.get("TimeControl") == "180+0"
            and int(headers.get("WhiteElo", 0)) > 2000):

            games.append({
                "white": headers["White"],
                "black": headers["Black"],
                "white_elo": headers["WhiteElo"],
                "black_elo": headers["BlackElo"],
                "result": headers["Result"],
                "opening": headers.get("Opening", ""),
                "moves": str(game.mainline_moves()),
            })
        if len(games) > 0 and len(games) % 1000 == 0:
            print(f"Finished {len(games)} games so far")
        if len(games) >= 50000:
            break

Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 1000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 2000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 3000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 4000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 5000 games so far
Finished 6000 games so far
Finished 6000 games so far
Finished 6000 games so far
Finished 6000 games so far
Finished 7000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 8000 games so far
Finished 9000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 10000 games so far
Finished 11000 games so far
Finished 11000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 12000 games so far
Finished 13000 games so far
Finished 13000 games so far
Finished 13000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 14000 games so far
Finished 15000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 16000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 17000 games so far
Finished 18000 games so far
Finished 18000 games so far
Finished 18000 games so far
Finished 18000 games so far
Finished 19000 games so far
Finished 19000 games so far
Finished 19000 games so far
Finished 20000 games so far
Finished 21000 games so far
Finished 21000 games so far
Finished 22000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 23000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 24000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 25000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far
Finished 26000 games so far

In [15]:
df_subset = pd.DataFrame(games)

In [17]:
df_subset['white_elo'].max()

'3024'

In [18]:
df_subset

,white,black,white_elo,black_elo,result,opening,moves
0,chandaje,Goldensmith,2148,2074,0-1,English Opening: Great Snake Variation,1. c4 { [%clk 0:03:00] } 1... g6 { [%clk 0:03:...
1,ARubinstein,konstant1ne,2218,2200,1-0,French Defense: Knight Variation,1. Nf3 { [%eval 0.1] [%clk 0:03:00] } 1... e6 ...
2,kamig,Chomuszka,2505,2483,1-0,"Rapport-Jobava System, with e6",1. d4 { [%eval 0.15] [%clk 0:03:00] } 1... d5 ...
3,wikoffense,makmak1984,2008,2073,1-0,Scandinavian Defense: Mieses-Kotroc Variation,1. e4 { [%clk 0:03:00] } 1... d5 { [%clk 0:03:...
4,savymoves,unpredictable2024,2057,2083,1-0,English Opening: King's English Variation,1. c4 { [%clk 0:03:00] } 1... e5 { [%clk 0:03:...
...,...,...,...,...,...,...,...
49995,gfelipe,ObiWanMakkaroni,2199,2103,1-0,Queen's Gambit Declined,1. d4 { [%clk 0:03:00] } 1... d5 { [%clk 0:03:...
49996,OJOSGOKKU2,zimchess_zw,2002,1960,0-1,Torre Attack: Classical Defense,1. d4 { [%clk 0:03:00] } 1... Nf6 { [%clk 0:03...
49997,jivie,WMcDog,2098,2043,0-1,Ruy Lopez: Steinitz Defense,1. e4 { [%clk 0:03:00] } 1... e5 { [%clk 0:03:...
49998,Leo_Mirana81,Klimchenko,2104,1804,1-0,Sicilian Defense: Portsmouth Gambit,1. e4 { [%clk 0:01:30] } 1... c5 { [%clk 0:03:...
49999,Natiq2011,awewe,2099,1512,1-0,Scandinavian Defense: Boehnke Gambit,1. e4 { [%clk 0:01:30] } 1... d5 { [%clk 0:03:...

In [37]:
df_subset["white_win"] = (df_subset["result"] == '1-0').astype(int)

,white,black,white_elo,black_elo,result,opening,moves,white_win
0,chandaje,Goldensmith,2148,2074,0-1,English Opening: Great Snake Variation,1. c4 { [%clk 0:03:00] } 1... g6 { [%clk 0:03:...,0
1,ARubinstein,konstant1ne,2218,2200,1-0,French Defense: Knight Variation,1. Nf3 { [%eval 0.1] [%clk 0:03:00] } 1... e6 ...,1
2,kamig,Chomuszka,2505,2483,1-0,"Rapport-Jobava System, with e6",1. d4 { [%eval 0.15] [%clk 0:03:00] } 1... d5 ...,1
3,wikoffense,makmak1984,2008,2073,1-0,Scandinavian Defense: Mieses-Kotroc Variation,1. e4 { [%clk 0:03:00] } 1... d5 { [%clk 0:03:...,1
4,savymoves,unpredictable2024,2057,2083,1-0,English Opening: King's English Variation,1. c4 { [%clk 0:03:00] } 1... e5 { [%clk 0:03:...,1
...,...,...,...,...,...,...,...,...
49995,gfelipe,ObiWanMakkaroni,2199,2103,1-0,Queen's Gambit Declined,1. d4 { [%clk 0:03:00] } 1... d5 { [%clk 0:03:...,1
49996,OJOSGOKKU2,zimchess_zw,2002,1960,0-1,Torre Attack: Classical Defense,1. d4 { [%clk 0:03:00] } 1... Nf6 { [%clk 0:03...,0
49997,jivie,WMcDog,2098,2043,0-1,Ruy Lopez: Steinitz Defense,1. e4 { [%clk 0:03:00] } 1... e5 { [%clk 0:03:...,0
49998,Leo_Mirana81,Klimchenko,2104,1804,1-0,Sicilian Defense: Portsmouth Gambit,1. e4 { [%clk 0:01:30] } 1... c5 { [%clk 0:03:...,1
49999,Natiq2011,awewe,2099,1512,1-0,Scandinavian Defense: Boehnke Gambit,1. e4 { [%clk 0:01:30] } 1... d5 { [%clk 0:03:...,1